/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreditLog } from "./CreditLog";
import { CreditLogCountArgs } from "./CreditLogCountArgs";
import { CreditLogFindManyArgs } from "./CreditLogFindManyArgs";
import { CreditLogFindUniqueArgs } from "./CreditLogFindUniqueArgs";
import { DeleteCreditLogArgs } from "./DeleteCreditLogArgs";
import { CreditLogService } from "../creditLog.service";
@graphql.Resolver(() => CreditLog)
export class CreditLogResolverBase {
  constructor(protected readonly service: CreditLogService) {}

  async _creditLogsMeta(
    @graphql.Args() args: CreditLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CreditLog])
  async creditLogs(
    @graphql.Args() args: CreditLogFindManyArgs
  ): Promise<CreditLog[]> {
    return this.service.creditLogs(args);
  }

  @graphql.Query(() => CreditLog, { nullable: true })
  async creditLog(
    @graphql.Args() args: CreditLogFindUniqueArgs
  ): Promise<CreditLog | null> {
    const result = await this.service.creditLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CreditLog)
  async deleteCreditLog(
    @graphql.Args() args: DeleteCreditLogArgs
  ): Promise<CreditLog | null> {
    try {
      return await this.service.deleteCreditLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
