/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaymentType } from "./PaymentType";
import { PaymentTypeCountArgs } from "./PaymentTypeCountArgs";
import { PaymentTypeFindManyArgs } from "./PaymentTypeFindManyArgs";
import { PaymentTypeFindUniqueArgs } from "./PaymentTypeFindUniqueArgs";
import { CreatePaymentTypeArgs } from "./CreatePaymentTypeArgs";
import { UpdatePaymentTypeArgs } from "./UpdatePaymentTypeArgs";
import { DeletePaymentTypeArgs } from "./DeletePaymentTypeArgs";
import { Store } from "../../store/base/Store";
import { PaymentTypeService } from "../paymentType.service";
@graphql.Resolver(() => PaymentType)
export class PaymentTypeResolverBase {
  constructor(protected readonly service: PaymentTypeService) {}

  async _paymentTypesMeta(
    @graphql.Args() args: PaymentTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PaymentType])
  async paymentTypes(
    @graphql.Args() args: PaymentTypeFindManyArgs
  ): Promise<PaymentType[]> {
    return this.service.paymentTypes(args);
  }

  @graphql.Query(() => PaymentType, { nullable: true })
  async paymentType(
    @graphql.Args() args: PaymentTypeFindUniqueArgs
  ): Promise<PaymentType | null> {
    const result = await this.service.paymentType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PaymentType)
  async createPaymentType(
    @graphql.Args() args: CreatePaymentTypeArgs
  ): Promise<PaymentType> {
    return await this.service.createPaymentType({
      ...args,
      data: {
        ...args.data,

        store: args.data.store
          ? {
              connect: args.data.store,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PaymentType)
  async updatePaymentType(
    @graphql.Args() args: UpdatePaymentTypeArgs
  ): Promise<PaymentType | null> {
    try {
      return await this.service.updatePaymentType({
        ...args,
        data: {
          ...args.data,

          store: args.data.store
            ? {
                connect: args.data.store,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PaymentType)
  async deletePaymentType(
    @graphql.Args() args: DeletePaymentTypeArgs
  ): Promise<PaymentType | null> {
    try {
      return await this.service.deletePaymentType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Store, {
    nullable: true,
    name: "store",
  })
  async getStore(@graphql.Parent() parent: PaymentType): Promise<Store | null> {
    const result = await this.service.getStore(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
